### ISSUE TITLE
[보완] 오늘의 표현 배치 애플리케이션으로 변경하도록 하기

### ISSUE THREAD

**Issue by Catnap421** [YAPP-18th/Android-Team-1-Backend#107]
### AS-IS 
날짜를 계산해서 오늘의 표현을 가져오도록 구성

### TO-BE
배치 애플리케이션으로 오늘의 표현을 바꿔주도록 구성

**Comment by NaLDo627** [comment]
따로 오늘의 표현 테이블로 분리하는 것도 방법일 것 같다.

**Comment by NaLDo627** [comment]
테이블 명 변경
TODAY_EXPRESSION -> USEFUL_EXPRESSION

새로운 테이블 생성 (오늘의 표현)
TODAY_USEFUL_EXPRESSION
