### ISSUE TITLE
[기능] 사용자 프로필 수정

### ISSUE THREAD

**Issue by Catnap421** [YAPP-18th/Android-Team-1-Backend#109]
## 기능 

- 사용자 닉네임 변경 
- 사용자 이미지 변경

## 고려사항

사용자가 프로필을 조회할 때, 해당 프로필이 본인의 것인지를 DTO에 필드로 반환해야 함

**Comment by NaLDo627** [comment]
프론트 편의성을 위해서, PATCH 메서드로 구현해보는 것도 좋을 것 같다!
