### ISSUE TITLE
[보완] 사용자 식별 프로퍼티 변경

### ISSUE THREAD

**Issue by Catnap421** [YAPP-18th/Android-Team-1-Backend#129]
### AS-IS
- 사용자 식별을 현재는 이메일로 하고 있음
[문제](https://devtalk.kakao.com/t/topic/49545?u=karl.lee&source_topic_id=54188)

### TO-BE
- 사용자 식별을 user_id로 변경할 것
- identifier로 식별자를 설정하되, 구글과 카카오에서 겹칠수가 있으므로, google_{id}, kakao_{id}로...?

## 할 일

- [x] OAuth 코드 변경
- [x] JWT 코드 변경

## 마감기한

2021.06.03

**Comment by NaLDo627** [comment]
이거 작업되면 RefreshToken 작업해야겠다!
