### ISSUE TITLE
[이슈] 쿠키 다중 획득 

### ISSUE THREAD

**Issue by Catnap421** [YAPP-18th/Android-Team-1-Backend#164]
## 문제

답변을 작성하고 삭제하고 다시 작성하면, 쿠키를 무한정으로 얻을 수 있음

## 예상 해결방안
1. 답변을 작성하고 삭제하면, 그 날은 다시 작성을 못하게 관리하는 방법
1.1. 새로 테이블을 만들어서 플래그 값을 저장 -> 배치를 통해 00시에 초기화를 해줘야 함
1.2. Redis를 연결해서, expiredat으로 자동으로 삭제되도록 관리하는 방법

2. 답변은 작성 가능하되, 쿠키를 하루에 하나만 획득가능하도록 관리하는 방법
 -> 프론트에서 글 작성하면 무조건 쿠키 획득 팝업을 띄우도록 짜서, 제한이 있어보임

**Comment by NaLDo627** [comment]
1번 방안으로 가려면 손이 많이 갈 것 같고, 실수로 삭제했을 경우에도 대응이 힘들 것 같아!
2번 방안이 좋아보이는데, 현재 murengCount를 통해  쿠키 수가 관리가 되기 때문에, 이 경우에는 머렝 쿠키 테이블을 따로 만들어서, 시간 관리를 해줘야 할 것 같아! 이전에 비슷한 요구사항이 있었던거 같은데, 현정이랑 정리해서 테이블을 새로 만드는 방향으로 고려해 보자.

**Comment by Catnap421** [comment]
테이블 새로 만드는 방향 접수!!
