### ISSUE TITLE
[리팩토링] EntityMapper 관련 수정

### ISSUE THREAD

**Issue by NaLDo627** [YAPP-18th/Android-Team-1-Backend#169]
현재 EntityMapper 에 각각의 상황에 맞는 매핑 로직을 모두 포함시키고 있다. (예, replyMapper의 경우, 매핑 메서드가 6개 이상임)
이를 적절한 상황에 맞게 분리하는 로직을 생각해봐야 한다.
EntityMapper 위에 서비스 로직을 추가하는 방안 생각중

**Comment by Catnap421** [comment]
![image](https://user-images.githubusercontent.com/30318917/125973137-ad084fda-c71f-4670-824a-ad9fc2516abc.png)
수많은 ignore = true를 알아보는 중..

방법은 찾았으나, 똑같은 source를 가진 인자가 제공될 경우, 문제가 발생함.. 클래스 나누기는 끝났으나, 맘에 안들어서 공식 문서 살펴보는 중.. ㅜ.ㅠ

**Comment by Catnap421** [comment]
다음주까지 뱃지 획득과 분리할 예정
