### ISSUE TITLE
[보완] 캐시 기능 도입

### ISSUE THREAD

**Issue by Catnap421** [YAPP-18th/Android-Team-1-Backend#206]
## 기능 
메인 페이지의 인기 답변과, 인기 질문을 가져올 때 지연 속도가 심함.
이를 위해 캐시 기능을 넣는 것을 고려 중

추가로 인기 순이라서, 사소한 것에도 순위가 변동될 수 있음.
인기 답변 말고 트렌드, 핫 이런 식으로 바꾸면 사용자입장에서도 더 적절하게 다가오지 않을까 하는데 이건 프론트랑 이야기를 해봐야 함.

## 할 일

caffeine 캐시 적용

**Comment by NaLDo627** [comment]
#174 중복인거 같네용
