### ISSUE TITLE
[기능] 질문에 대한 답변 상세 조회

### ISSUE THREAD

**Issue by NaLDo627** [YAPP-18th/Android-Team-1-Backend#28]
## 기능 
특정 질문에 대해서 답변 상세 내용을 조회할 수 있다. 
writing/done 뷰 참고

**Comment by Catnap421** [comment]
![image](https://user-images.githubusercontent.com/30318917/118086007-4247d100-b3fe-11eb-976d-d407acd70d97.png)
있어야 할 정보
- 질문명
- 답변
- 답변 작성자
- 좋아요 수
- 등록(수정) 날짜

**Comment by NaLDo627** [comment]
ReplyDto 를 변경해서 있어야할 정보를 모두 담을수 있도록 변경했다.

**Comment by Catnap421** [comment]
엔드포인트 : /api/reply/{replyId}
