### ISSUE TITLE
[기능] 내가 얻은 성과(쿠키) 조회

### ISSUE THREAD

**Issue by NaLDo627** [YAPP-18th/Android-Team-1-Backend#31]
## 기능 
내가 얻은 성과, 쿠키를 조회할 수 있다.

**Comment by Catnap421** [comment]
제한사항
1. 쿠키에 대한 이미지가 존재한다.
2. 쿠키의 이미지(or 색)은 모두 다르다.

**Comment by Catnap421** [comment]
#64 현재 사용자의 정보를 가져오는 API로 대신할 수 있을듯
