### ISSUE TITLE
[보완] 쓰기용, 읽기용 DTO 분리

### ISSUE THREAD

**Issue by NaLDo627** [YAPP-18th/Android-Team-1-Backend#70]
### AS-IS
- 쓰기용, 읽기용 DTO 구분없이 하나로 모두 사용하고 있다. 그러다 보니, 문서 상에서의 차이가 명확하지 않고, 읽기용 필드의 경우에서는 어쩔 수 없이 Swagger상에서 누락시켜야 했다. (Swagger 상에서 분리할 수 있는 방법이 있는지 찾아보았지만 못찾았다..)

### TO-BE
- 쓰기용, 읽기용 DTO를 구분한다. 이때 관련 매퍼에서 설정을 추가시켜 주어야 한다. 최대한 중복되지 않게 하려면 고민 많이 해야할 것 같다..

**Comment by Catnap421** [comment]
https://meetup.toast.com/posts/213
MapStruct라는 것도 ModelMapper 대신 사용 많이 한다고 하더라고 나중에 이걸로 바꿔보는 것도 괜찮지 않을까?

**Comment by NaLDo627** [comment]
오우 참고해볼게!

**Comment by NaLDo627** [comment]
MapStruct 봤는데 ModelMapper 보다 더 간결하고 좋아보이네..!
